#!/bin/bash

# Definir la variable para el alias
$mainPath="/etc/vpsmanager"
ALIAS_NAME="adm"
MENU_PATH="$mainPath/adm.sh"
ALIAS_COMMAND="sudo $MENU_PATH"

#--- FUNCION BARRAS DE INSTALACION
barra_intall() {
    comando="$1"
    _=$(
        $comando >/dev/null 2>&1
    ) &
    >/dev/null
    pid=$!
    while [[ -d /proc/$pid ]]; do
        echo -ne " \033[1;33m["
        for ((i = 0; i < 20; i++)); do
            echo -ne "\033[1;31m##"
            sleep 0.2
        done
        echo -ne "\033[1;33m]"
        sleep 1s
        echo
        tput cuu1
        tput dl1
    done
    echo -ne " \033[1;33m[\033[1;31m########################################\033[1;33m] - \033[1;32m100%\033[0m\n"
    sleep 1s
}

dependencias() {
    dpkg --configure -a >/dev/null 2>&1
    apt -f install -y >/dev/null 2>&1
    packages="zip unzip python python3 python3-pip openssl iptables lsof pv boxes at mlocate gawk bc jq npm nodejs socat net-tools cowsay figlet lolcat git"
    for i in $packages; do
        paquete="$i"
        echo -e "\033[1;97m        INSTALANDO PAQUETE \e[93m >>> \e[36m $i"
        barra_intall "apt-get install $i -y"
    done
}

install_paquetes() {
    clear && clear
    msgi -bar2
    echo -e " \e[33m\e[5m\033[1;100m   =====>> ►►  🖥  SCRIPT | LXManager  🖥  ◄◄ <<=====   \033[1;37m"
    msgi -bar
    echo -e "  \033[1;41m    -- INSTALACION DE PAQUETES PARA LXManager --   \e[49m"
    msgi -bar
    dependencias
    echo -e "\e[1;97m          REMOVIENDO PAQUETES OBSOLETOS \e[1;32m"
    barra_intall "apt autoremove -y "
    echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
    echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections
    msgi -bar2
    read -t 30 -n 1 -rsp $'\033[1;97m           Preciona Enter Para continuar\n'
}

instalacionInicial() {
    clear && clear
    #CARPETAS PRINCIPALES
    mkdir -p $mainPath >/dev/null 2>&1
    mkdir -p $mainPath/temp >/dev/null 2>&1
    mkdir -p $mainPath/filespy >/dev/null 2>&1
    mkdir -p $mainPath/botmanager >/dev/null 2>&1
    mkdir -p $mainPath/PortM >/dev/null 2>&1
    mkdir -p $mainPath/v2ray >/dev/null 2>&1
    mkdir -p /root/.ssh >/dev/null 2>&1

    install_paquetes
}

instalacionInicial


# Clonar el repositorio en un directorio temporal
git clone https://github.com/Angel892/vpsmanager.git $mainPath
if [ $? -ne 0 ]; then
    echo "Error: La clonación del repositorio falló."
    exit 1
fi

# Dar permisos de ejecución al script principal y a los scripts de funciones de manera recursiva
sudo find $mainPath/ -type f -name "*.sh" -exec chmod +x {} \;
if [ $? -ne 0 ]; then
    echo "Error: No se pudieron asignar los permisos de ejecución."
    exit 1
fi

alias1="/usr/bin/adm"
alias2="/usr/bin/ADM"

if [ -e "$alias1" ]; then
    sudo rm $alias1
    echo "$MENU_PATH" >$alias1 && chmod +x $alias1
else
    echo "$MENU_PATH" >$alias1 && chmod +x $alias1
fi

if [ -e "$alias2" ]; then
    sudo rm $alias2
    echo "$MENU_PATH" >$alias2 && chmod +x $alias2
else
    echo "$MENU_PATH" >$alias2 && chmod +x $alias2
fi

# Ejecutar el script principal desde su nueva ubicación (evitar usando exec para mantener la sesión)
$ALIAS_COMMAND
if [ $? -ne 0 ]; then
    echo "Error: Falló la ejecución del script principal."
    exit 1
fi
